name: "Daily Fudan"

on:
  schedule:
    - cron: "27 15 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'true'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install requirements
        run: pip install -r ./requirements.txt

      - name: Run sign
        run: python3 ./dailyFudan.py ${{ secrets.FUDAN }}
