name: "Daily Fudan"

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install requirements
        run: pip install -r ./requirements.txt

      - name: Run sign
        run: |
         python3 ./dailyFudan.py '${{ secrets.LIANG }}'
         python3 ./dailyFudan.py '${{ secrets.LINX }}'
         python3 ./dailyFudan.py '${{ secrets.ZZG }}'
